run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - runs
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
  govet:
    check-shadowing: true
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: error
  staticcheck:
    checks: ["all", "-SA1019"]

linters:
  enable:
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - varcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0

